### ISSUE TITLE
Cannot find the ligand-receptor interaction database named 'lrc2p'.

### ISSUE THREAD

**Issue by beccasimmons** [asrhou/NATMI#20]
Hi,

I am trying to use NATMI and have the following error when trying to use ExtractEdges.py "Cannot find the ligand-receptor interaction database named 'lrc2p'.". I have a .csv file in in the lrdbs folder but even when I point to it I get the same error. 

Thanks,
Becca

**Comment by asrhou** [comment]
Hi there, please try to run any Python script in the NATMI folder. Currently, Python compiler only finds the ligand-receptor interaction database folder from the directory where the command is called. Therefore, Python compiler cannot find the database folder if the script is executed not in the NATMI's home directory.
