### ISSUE TITLE
Some requirements

### ISSUE THREAD

**Issue by Landau1994** [asrhou/NATMI#30]
Hi, NATMI is very easy to use. here I have some requirements:

- Can the NATMI team remove the intermediate file， because the output directory is very large and most of which are intermediate files? Most users don't care about the intermediate file.
-  Can the NATMI team provided other Organism L-R pairs? Because the ID transfer step is like a black box, it will be useful to directly provide other organisms (like  mouse, taxid:10090) L-R pairs, 

Thanks!

**Comment by asrhou** [comment]
Hi, thank you for your suggestions! We will add more organism L-R pair databases and allow the user to control if the intermediate files will be generated.
