### ISSUE TITLE
Help adjusting network visualisation

### ISSUE THREAD

**Issue by jdarmitage** [asrhou/NATMI#31]
Hi,

Thanks for this brilliant tool for Single cell analysis. I'm trying to generate a delta network that contains a lot of edges/nodes and I'm finding that because the network is so dense it's difficult to read the text or discern the significant edges in red or blue (see example below). Is there a way to generate the plots so specific elements appear above others? Like the text annotations and significant edges? Is it possible to hide edges/nodes if they're not significant?

![image](https://user-images.githubusercontent.com/63338320/98635629-4ff1a080-2360-11eb-9372-288da2d8db1d.png)

Thanks again!

**Comment by asrhou** [comment]
Has been addressed through emails.
