### ISSUE TITLE
Selection criteria of significant results

### ISSUE THREAD

**Issue by ZxyChopcat** [asrhou/NATMI#35]
Hi,
I appreciate the tool NATMI that you have developed.I have a quesion related to the selection criteria of significant results.
In brief, what is the number of edge expression weight larger than that could be considered significant?For example,I run some data of patients and healthy controls using NATMI,getting many data with high "Delta edge expression weight" value.However,many of them have low value of edge expression weight either in patients and healthy controls.I wonder how you filter meaningless values out in this condition.
In addition,should I discard those pairs with high specificity but low expression level?
My codes for NATMI are as follows:
python ExtractEdges.py --species human --emFile /home/NATMI/NATMI-spH-matrix.csv --annFile /home/NATMI/NATMI-spH-anno.csv --coreNum 4 --out /home/NATMI/outHCdefult
python ExtractEdges.py --species human --emFile /home/NATMI/NATMI-spP-matrix.csv --annFile /home/NATMI/NATMI-spP-anno.csv --coreNum 4 --out /home/NATMI/outpatientdefult
python DiffEdges.py --refFolder /home/NATMI/outHCdefult --targetFolder /home/NATMI/outpatientdefult --out /home/NATMI/outcomparedefult
Thank you very much!

**Comment by asrhou** [comment]
Hi, it depends on the platform used to obtain your data. As long as the expression levels of those genes are higher than the expected expression threshold, you cannot drop them.

**Comment by XYZuo** [comment]
Thanks for your reply!
