### ISSUE TITLE
Gene referenced in the database that did not show up after computing ExtractEdges.py

### ISSUE THREAD

**Issue by rmathieu25** [asrhou/NATMI#41]
Hello,

First of all, I would like to thank you for developing NATMI, It is really a great tool!!

Nevertheless, I have an issue that I do not understand. I have five mouse datasets and in each one of them the gene Nrg1 is expressed so this gene is present in my Normalized Expression Data that I give as an input of the ExtractEdges.py script. Although Nrg1 is present in the database and in your homogene.data file,  in the result table, the Nrg1 gene does not show up in any of my five datasets. Do you have any idea what can be the issue?

As an example,here is the command line that I used : 

```
python ExtractEdges.py --interSpecies expandp --interDB LRDB_NATMI --emFile P56wt_counts_norm.txt --annFile P56wt_metadata.txt --species mouse --coreNum 10 --out P56_wt
```
Thank you very much in advance.
Have a good evening.

**Comment by asrhou** [comment]
Resolved through emails.
